/* istanbul ignore file */

import {Bytes, fixed_list, int8s, list, LVBytes, LVList, uint_t, uint8_t, uint16_t, uint24_t, uint32_t, uint64_t, WordList} from './basic';
import {
    Bool,
    BlzApsOption,
    BlzBindingType,
    BlzConcentratorType,
    BlzConfigTxPowerMode,
    BlzCounterType,
    BlzCurrentSecurityBitmask,
    BlzDerivedKeyType,
    BlzDeviceUpdate,
    BlzEUI64,
    BlzEventUnits,
    BlzGpKeyType,
    BlzGpSecurityLevel,
    BlzIncomingMessageType,
    BlzInitialSecurityBitmask,
    BlzJoinDecision,
    BlzJoinMethod,
    BlzKeyStatus,
    BlzKeyStructBitmask,
    BlzKeyType,
    BlzLibraryStatus,
    BlzMacPassthroughType,
    BlzMulticastId,
    BlzNetworkInitBitmask,
    BlzNetworkStatus,
    BlzNodeId,
    BlzNodeType,
    BlzOutgoingMessageType,
    BlzPanId,
    BlzRf4ceApplicationCapabilities,
    BlzRf4ceNodeCapabilities,
    BlzRf4ceTxOption,
    BlzStackError,
    BlzStatus,
    BlzZDOCmd,
    BlzZdoConfigurationFlags,
    BlzZllKeyIndex,
    BlzZllState,
    BlzConfigId,
    BlzDecisionId,
    BlzEndpointFlags,
    BlzExtendedValueId,
    BlzMfgTokenId,
    BlzNetworkScanType,
    BlzPolicyId,
    BlzSourceRouteOverheadInformation,
    BlzValueId,
    BlzZllNetworkOperation,
    NcpResetCode,
    SecureBlzRandomNumber,
    SecureBlzSecurityLevel,
    SecureBlzSecurityType,
    SecureBlzSessionId,
    SLStatus,
} from './named';
import {
    BlzAesMmoHashContext,
    BlzApsFrame,
    BlzBindingTableEntry,
    BlzCertificate283k1Data,
    BlzCertificateData,
    BlzCurrentSecurityState,
    BlzGpAddress,
    BlzGpSinkListEntry,
    BlzInitialSecurityState,
    BlzKeyData,
    BlzKeyStruct,
    BlzMessageDigest,
    BlzMultiAddress,
    BlzMulticastTableEntry,
    BlzNeighbors,
    BlzNeighborTableEntry,
    BlzNetworkInitStruct,
    BlzNetworkParameters,
    BlzNodeDescriptor,
    BlzPrivateKey283k1Data,
    BlzPrivateKeyData,
    BlzPublicKey283k1Data,
    BlzPublicKeyData,
    BlzRf4ceApplicationInfo,
    BlzRf4cePairingTableEntry,
    BlzRf4ceVendorInfo,
    BlzRouteTableEntry,
    BlzRoutingTable,
    BlzRoutingTableEntry,
    BlzSecurityManagerContext,
    BlzSecurityManagerNetworkKeyInfo,
    BlzSignature283k1Data,
    BlzSignatureData,
    BlzSimpleDescriptor,
    BlzSmacData,
    BlzTokTypeStackZllData,
    BlzTokTypeStackZllSecurity,
    BlzZigbeeNetwork,
    BlzZllAddressAssignment,
    BlzZllDeviceInfoRecord,
    BlzZllInitialSecurityState,
    BlzZllNetwork,
    BlzZllSecurityAlgorithmData,
    BlzStruct,
} from './struct';

/* eslint-disable-next-line @typescript-eslint/no-explicit-any*/
export function deserialize(payload: any, schema: any[]): any[] {
    const result = [];
    let value,
        data = payload;
    for (const type of schema) {
        [value, data] = type.deserialize(type, data);
        result.push(value);
    }
    return [result, data];
}

/* eslint-disable-next-line @typescript-eslint/no-explicit-any*/
export function serialize(data: any[], schema: {serialize: (schema: any, item: any) => Buffer}[]): Buffer {
    return Buffer.concat(schema.map((s, idx) => s.serialize(s, data[idx])));
}

export {
    /* Basic Types */
    int8s,
    uint_t,
    uint8_t,
    uint16_t,
    uint24_t,
    uint32_t,
    uint64_t,
    LVBytes,
    list,
    LVList,
    fixed_list,
    WordList,
    Bytes,

    /* Named Types */
    NcpResetCode,
    BlzRf4ceTxOption,
    BlzRf4ceNodeCapabilities,
    BlzRf4ceApplicationCapabilities,
    BlzNodeId,
    BlzPanId,
    BlzMulticastId,
    BlzEUI64,
    BlzLibraryStatus,
    SecureBlzSecurityType,
    SecureBlzSecurityLevel,
    BlzGpSecurityLevel,
    BlzGpKeyType,
    SecureBlzRandomNumber,
    SecureBlzSessionId,
    Bool,
    BlzConfigId,
    BlzValueId,
    BlzExtendedValueId,
    BlzEndpointFlags,
    BlzConfigTxPowerMode,
    BlzPolicyId,
    BlzDecisionId,
    BlzMfgTokenId,
    BlzStatus,
    SLStatus,
    BlzStackError,
    BlzEventUnits,
    BlzNodeType,
    BlzNetworkStatus,
    BlzIncomingMessageType,
    BlzOutgoingMessageType,
    BlzMacPassthroughType,
    BlzBindingType,
    BlzApsOption,
    BlzNetworkScanType,
    BlzJoinDecision,
    BlzInitialSecurityBitmask,
    BlzCurrentSecurityBitmask,
    BlzKeyType,
    BlzKeyStructBitmask,
    BlzDeviceUpdate,
    BlzKeyStatus,
    BlzCounterType,
    BlzJoinMethod,
    BlzZdoConfigurationFlags,
    BlzConcentratorType,
    BlzZllState,
    BlzZllKeyIndex,
    BlzZllNetworkOperation,
    BlzSourceRouteOverheadInformation,
    BlzNetworkInitBitmask,
    BlzZDOCmd,
    BlzDerivedKeyType,

    /* Structs */
    BlzStruct,
    BlzNetworkParameters as BlzNetworkParameters,
    BlzZigbeeNetwork,
    BlzApsFrame,
    BlzBindingTableEntry,
    BlzMulticastTableEntry,
    BlzKeyData,
    BlzCertificateData,
    BlzPublicKeyData,
    BlzPrivateKeyData,
    BlzSmacData,
    BlzSignatureData,
    BlzCertificate283k1Data,
    BlzPublicKey283k1Data,
    BlzPrivateKey283k1Data,
    BlzSignature283k1Data,
    BlzMessageDigest,
    BlzAesMmoHashContext,
    BlzNeighborTableEntry,
    BlzRouteTableEntry,
    BlzInitialSecurityState,
    BlzCurrentSecurityState,
    BlzKeyStruct,
    BlzNetworkInitStruct,
    BlzZllSecurityAlgorithmData,
    BlzZllNetwork,
    BlzZllInitialSecurityState,
    BlzZllDeviceInfoRecord,
    BlzZllAddressAssignment,
    BlzTokTypeStackZllData,
    BlzTokTypeStackZllSecurity,
    BlzRf4ceVendorInfo,
    BlzRf4ceApplicationInfo,
    BlzRf4cePairingTableEntry,
    BlzGpAddress,
    BlzGpSinkListEntry,
    BlzNodeDescriptor,
    BlzSimpleDescriptor,
    BlzMultiAddress,
    BlzNeighbors,
    BlzRoutingTable,
    BlzRoutingTableEntry,
    BlzSecurityManagerContext,
    BlzSecurityManagerNetworkKeyInfo,
};
